language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
install:
  - echo  "Reached Install Section"

script:
  - echo "Reached Script Section"
  - gcc   	Array_math.c degree.c Fib_Def.c  Main.c -o output
  - ./output
  - size output
  - echo "Reached Script Section - cunit_democode"
  - gcc   	Array_math_cunit.c -o Array_math_cunit_JG -lcunit
  - ./Array_math_cunit_JG
  - size Array_math_cunit_JG
  